#!/bin/bash
#echo "$1"
if [ "$1" = "-?" ]
then
	echo 'strcount [filename]'
	echo 'Count lines in given file'
	echo
else
	declare -i i=0
	while read line           
	do      
		i=$((i + 1))    
    		#echo "$line"           
	done <"$1"
	echo $i   
fi
